name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}] # every 12 hours
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: prosperousdibakoane
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Johannesburg
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_streak: yes
          plugin_habits: yes
          plugin_music: yes
          plugin_music_provider: apple
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: detailed
